language: node_js
node_js:
    - '14.16'
cache: yarn
script:
    - echo 'Deploy!!'
    - echo 'Installing Deps!'
    - yarn
    - echo 'Testing!'
    - yarn test
    - yarn run build

deploy:
    provider: heroku
    api_key:
        secure: 'GF6VDqfFt7RUd5GU7wQiTFXJbTicj8iFsQUcx5vnsY4k8YR9moWbBOrNhSXkWnDh0VUT32Pndl7UsPMyaDrJ4sj8XDaEgLyyMg8OU9+qEr/D4031f+NgwxbdixTK9Gdat3gZCk+WGxsQbn9nkgPSjH5UD1nspAnxm07MRMeTq8z8Q81Qv0m9pj4NVQjHJcAhG3OUDHgK0Jvv5C5XJJ5iwEX4JNO4oFS5TJ/GoiBasmuFeSdQLfSK7gnjrjckE/8WDoJBiOL+cJpxULdZIj6A2ulGFapo1R/4dMz7cPynxTM1KoMozOhofnc2ZjYld783RazjWwHyVak+0zK1YYTb05p3tRHFxWTyCl9Aqrn8XRi2hbEL8+GdCy/SApvp4DlXtr/A+YFJF8A68P5sd15kRyeIg6tivg2dgybhZmUrb2vFr0Q+prwGjg0riVniMJ+1QbMFcpq72nF7U7LL2hP7eRwsAW3DtgfWGK0II4qbOGZWOU1N+/eIKCM9D1wk3doz/j/kf8MSA4utp0to3gh6q0TIQz4aaiEZQWHNx0zv9Bicriyvyzo9b1x4SiO44bUv0sdcxveivUia+JFOxrNhBPPOKqPGDSwZubqbAH+2+7/ALt/dYFsrw91dSuolFMPY8Iq9FvX4tNAJPu4VHcyjrhFKB6P06ZwY6tBgSnWCHak='
    app: spacex-programs-lobo
    on:
        repo: croiden/spacex-program
