// @flow
export const FETCH_PROGRAMS: 'FETCH_PROGRAMS' = 'FETCH_PROGRAMS'
export const FETCH_PROGRAMS_SUCCESS: 'FETCH_PROGRAMS_SUCCESS' = 'FETCH_PROGRAMS_SUCCESS'
export const FETCH_PROGRAMS_FAILURE: 'FETCH_PROGRAMS_FAILURE' = 'FETCH_PROGRAMS_FAILURE'
